# Generated by Django 3.1.7 on 2021-03-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tagging', '0003_adapt_max_tag_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='addproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('uploadimg', models.ImageField(upload_to='uploads/')),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('edndate', models.DateTimeField()),
                ('tags', models.ManyToManyField(related_name='photos', to='tagging.Tag')),
            ],
        ),
    ]
