# Generated by Django 3.1.7 on 2021-03-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproject',
            name='total_target',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
