# Generated by Django 3.1.7 on 2021-03-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0003_auto_20210317_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproject',
            name='id_user',
            field=models.IntegerField(null=True),
        ),
    ]
